// ■ 設定: カテゴリIDと表示名のリスト (25単語ずつに分割)
const categoryList = {
    "S1": "Session 1 (ID 776 - 800)",
    "S2": "Session 2 (ID 801 - 825)",
    "S3": "Session 3 (ID 826 - 850)",
    "S4": "Session 4 (ID 851 - 875)",
    "all": "📚 すべての問題 (100単語)"
};

// ■ データ: 問題リスト
// q: 英単語, ans_j: 正解の日本語訳, example: 例文
const wordData = [
    // --- Session 1 (ID 776 - 800) ---
    { id: "S1-1", cat: "S1", q: "prove", ans_j: "証明する，明らかにする", example: "The experiment proved that his theory was right. (その実験は彼の理論が正しいことを証明した)" },
    { id: "S1-2", cat: "S1", q: "improve", ans_j: "改善する", example: "The software was improved to make it more user-friendly. (そのソフトはユーザーが使い易くなるように改良された)" },
    { id: "S1-3", cat: "S1", q: "prevent", ans_j: "防ぐ，妨げる", example: "They gave up the race to prevent further damage to the engine. (エンジンがそれ以上損傷するのを防ぐため，かれらはレースをあきらめた)" },
    { id: "S1-4", cat: "S1", q: "compare", ans_j: "比べる", example: "You can't compare the value of life. (生命の価値を比べることはできない)" },
    { id: "S1-5", cat: "S1", q: "detect", ans_j: "検知（検出）する", example: "This sensor detects light that human eyes cannot see. (このセンサーは人間の目に見えない光を検知する)" },
    { id: "S1-6", cat: "S1", q: "identify", ans_j: "識別する", example: "This system requires a password to identify the user. (このシステムはユーザーを識別するためにパスワードを要求します)" },
    { id: "S1-7", cat: "S1", q: "tidy", ans_j: "整然とした，整頓する", example: "You must always keep the lab tidy to prevent accidents. (事故防止のため，研究室は常に整然とした状態でなければいけない)" },
    { id: "S1-8", cat: "S1", q: "rapid", ans_j: "速い，素早い", example: "This rapid cooling system can make a lot of ice in a short time. (この急速冷却システムは短時間で大量の氷を作ることができる)" },
    { id: "S1-9", cat: "S1", q: "mobile", ans_j: "移動可能な，流動的な", example: "An electric current is described as a flow of mobile electrons. (電流は可動電子の流れとして説明される)" },
    { id: "S1-10", cat: "S1", q: "prime", ans_j: "最も重要な，全盛期", example: "Our prime concern is how rapidly the number of mobile phones will increase. (私たちの最大の関心事は，携帯電話の数がどれだけ速く増えるのかということだ)" },
    { id: "S1-11", cat: "S1", q: "major", ans_j: "主要な，専攻科目，専攻する", example: "Major issues of education in Japan were discussed in the conference. (会議では日本の教育における主要な問題が話し合われた)" },
    { id: "S1-12", cat: "S1", q: "minor", ans_j: "あまり重要ではない，小さい方の", example: "There are only minor differences between these two models. (この２つのモデルにはわずかな違いしかありません)" },
    { id: "S1-13", cat: "S1", q: "recent", ans_j: "最近の", example: "Recent cell phones have different shapes. (最近の携帯電話はさまざまな形をしている)" },
    { id: "S1-14", cat: "S1", q: "various", ans_j: "さまざまな", example: "Various materials were examined to produce a new type of fuel cell. (新しいタイプの燃料電池を作り出すためにさまざまな材料が調べられた)" },
    { id: "S1-15", cat: "S1", q: "former", ans_j: "以前の，先の，前者", example: "The former president died recently. (先代の社長が最近亡くなりました)" },
    { id: "S1-16", cat: "S1", q: "modern", ans_j: "現代の，近代的な", example: "The size of modern TV screens is larger than that of the old ones. (現代のテレビ画面の大きさは昔のものより大きい)" },
    { id: "S1-17", cat: "S1", q: "artificial", ans_j: "人工の", example: "Thousands of artificial satellites are currently orbiting the earth. (現在，数千個の人工衛星が地球を回っています)" },
    { id: "S1-18", cat: "S1", q: "automatic", ans_j: "自動の", example: "An automatic recording system starts when you enter the room. (その部屋に入ると自動録音システムが作動します)" },
    { id: "S1-19", cat: "S1", q: "available", ans_j: "入手可能な，利用できる", example: "Fuel cells will be available at stores soon. (燃料電池はもうすぐ店で買えるようになるだろう)" },
    { id: "S1-20", cat: "S1", q: "potential", ans_j: "潜在的な，潜在能力，可能性", example: "The potential demand for this product is quite large. (この製品に対する潜在的な需要はかなり大きい)" },
    { id: "S1-21", cat: "S1", q: "kinetic", ans_j: "運動の", example: "Kinetic energy exists whenever an object is in motion. (運動エネルギーは物体が運動しているときには必ず存在する)" },
    { id: "S1-22", cat: "S1", q: "medical", ans_j: "医療の，医学の", example: "I am studying medical technology. (私は医療技術を学んでいます)" },
    { id: "S1-23", cat: "S1", q: "nuclear", ans_j: "原子力の，（原子）核の", example: "There are no nuclear power stations in that country. (その国は原子力発電所がない)" },
    { id: "S1-24", cat: "S1", q: "chemical", ans_j: "化学の", example: "The two substances caused a chemical reaction. (その２つの物質が化学反応を起こした)" },
    { id: "S1-25", cat: "S1", q: "trick", ans_j: "手品，いんちき，（人を）だます", example: "Several tricks can be played with chemical substances. (化学物質を使っていくつかの手品ができます)" },

    // --- Session 2 (ID 801 - 825) ---
    { id: "S2-1", cat: "S2", q: "lecture", ans_j: "講義，講演", example: "I have heard his lecture at the university. (私は大学で彼の講義を聞いたことがある)" },
    { id: "S2-2", cat: "S2", q: "movement", ans_j: "運動，動くこと", example: "The sensor detects the movement of animals and turns the lights on. (センサーが動物の動きを感知し，ライトを点灯する)" },
    { id: "S2-3", cat: "S2", q: "politics", ans_j: "政治（学）", example: "Although the politician didn't major in politics, he is now a good political leader. (その政治家は政治学を専攻しなかったが，今や優れた政治リーダーだ)" },
    { id: "S2-4", cat: "S2", q: "copyright", ans_j: "著作権，版権", example: "Who has the copyright on this book? (誰がこの本の著作権を持っているのですか)" },
    { id: "S2-5", cat: "S2", q: "law", ans_j: "法律，法則", example: "The lawyer knows copyright law well. (その弁護士は著作権法に詳しい)" },
    { id: "S2-6", cat: "S2", q: "policy", ans_j: "方針，政策", example: "Our president has a solid policy on business. (うちの社長はビジネスに対してしっかりした方針を持っている)" },
    { id: "S2-7", cat: "S2", q: "ministry", ans_j: "省庁", example: "The news was released by the Foreign Ministry. (そのニュースは外務省から発表された)" },
    { id: "S2-8", cat: "S2", q: "expert", ans_j: "専門家，熟練者", example: "Many computer experts work in this company. (この会社では多くのコンピューターの専門家が働いている)" },
    { id: "S2-9", cat: "S2", q: "domain", ans_j: "領域（ドメイン），分野", example: "His expertise is in the domain of educational technology. (彼の専門分野は教育工学の領域だ)" },
    { id: "S2-10", cat: "S2", q: "region", ans_j: "地方，地域", example: "A strong earthquake and tsunami hit the Tohoku region in March 2011. (2011年3月に強い地震と津波が東北地方を襲った)" },
    { id: "S2-11", cat: "S2", q: "trade", ans_j: "取引，貿易，取引する", example: "Our company is interested in foreign trade. (わが社は海外との取引に興味がある)" },
    { id: "S2-12", cat: "S2", q: "tax", ans_j: "税金，課税する", example: "About two thirds of a cigarette's price is tax. (タバコの値段の約3分の2は税金だ)" },
    { id: "S2-13", cat: "S2", q: "bank", ans_j: "銀行，土手", example: "A bank does not always lend you money. (銀行はいつでもお金を貸してくれるわけではない)" },
    { id: "S2-14", cat: "S2", q: "institute", ans_j: "研究所，学協会", example: "Noguchi Hideyo once worked at the Rockefeller Institute for Medical Research. (野口英世はロックフェラー医学研究所で働いていたことがある)" },
    { id: "S2-15", cat: "S2", q: "government", ans_j: "政府", example: "The government passed a new tax law. (政府は新しい税法案を通過させた)" },
    { id: "S2-16", cat: "S2", q: "bureau", ans_j: "事務局", example: "She is working in the bureau in the city hall. (彼女は市役所の事務局で働いている)" },
    { id: "S2-17", cat: "S2", q: "account", ans_j: "（銀行の）口座，会計，説明する", example: "I opened an account at the bank. (私はその銀行に口座を開いた)" },
    { id: "S2-18", cat: "S2", q: "community", ans_j: "地域社会，共同社会", example: "The community has its own cable TV network. (その地域社会には独自のケーブルテレビ網がある)" },
    { id: "S2-19", cat: "S2", q: "committee", ans_j: "委員会", example: "The government formed a committee of experts. (政府は専門家による委員会を作った)" },
    { id: "S2-20", cat: "S2", q: "subject", ans_j: "主題，被験者", example: "The subject of our presentation is the history of community. (私たちの発表の主題は地域社会の歴史です)" },
    { id: "S2-21", cat: "S2", q: "experience", ans_j: "経験，経験する", example: "He wrote a book about his own experiences. (彼は自分自身の体験についての本を書いた)" },
    { id: "S2-22", cat: "S2", q: "pond", ans_j: "池，沼", example: "There are many artificial ponds in this region. (この地域には多くの人工池がある)" },
    { id: "S2-23", cat: "S2", q: "forest", ans_j: "森林", example: "The largest area of forest in the world is in Russia. (世界最大の森林地帯はロシアにあります)" },
    { id: "S2-24", cat: "S2", q: "period", ans_j: "期間，周期", example: "The nuclear reactor will stop for the period of January to March. (その原子炉は1月から3月までの期間停止します)" },
    { id: "S2-25", cat: "S2", q: "vapor", ans_j: "蒸気", example: "When water is heated, it changes into vapor. (水は熱せられると水蒸気に変わる)" },
    
    // --- Session 3 (ID 826 - 850) ---
    { id: "S3-1", cat: "S3", q: "mist", ans_j: "霧，もや，かすみ", example: "The temperature can be lowered by making artificial mist. (人工的に霧を発生させることで気温を下げることができる)" },
    { id: "S3-2", cat: "S3", q: "agency", ans_j: "作用，代理店", example: "Water becomes vapor by the agency of heat. (水は熱の作用で水蒸気になる)" },
    { id: "S3-3", cat: "S3", q: "attempt", ans_j: "試みる，企てる，試み，企て", example: "He is attempting to clarify the mechanism of aging. (彼は老化の仕組みを解明しようとしている)" },
    { id: "S3-4", cat: "S3", q: "injure", ans_j: "けがをさせる，傷つける", example: "A lot of people were injured in the accident. (多くの人がその事故でけがをした)" },
    { id: "S3-5", cat: "S3", q: "protect", ans_j: "守る，保護する", example: "Wear the helmet to protect your head from falling rocks. (落石から頭を守るためにヘルメットをかぶりなさい)" },
    { id: "S3-6", cat: "S3", q: "heal", ans_j: "治る，癒す，治す", example: "It took two weeks for my eye injury to heal. (目のけがが治るのに2週間かかった)" },
    { id: "S3-7", cat: "S3", q: "master", ans_j: "習得する，主人，達人", example: "Don't think you can master English in such a short period. (そんな短い期間で英語を習得できると思わないでください)" },
    { id: "S3-8", cat: "S3", q: "lock", ans_j: "施錠する，錠", example: "All the doors in this building can be locked with this master key. (このマスターキーでこのビルのすべてのドアを施錠できます)" },
    { id: "S3-9", cat: "S3", q: "reveal", ans_j: "明らかにする", example: "The newspaper revealed our company's scandal. (新聞はわが社の汚職事件を明らかにした)" },
    { id: "S3-10", cat: "S3", q: "strike", ans_j: "打つ，叩く", example: "With this tool, you can strike nails much faster than with a hammer. (この道具を使えば金づちを使うよりずっと速く釘を打つことができます)" },
    { id: "S3-11", cat: "S3", q: "occur", ans_j: "起こる，生ずる", example: "Serious nuclear accidents have occurred in America, Russia, and Japan. (これまでの大きな原子力事故は，アメリカ，ロシア，そして日本で起こりました)" },
    { id: "S3-12", cat: "S3", q: "oppose", ans_j: "反対する，対抗する，向かい合う", example: "The local people opposed the building of a nuclear plant. (地元の住民は原発の建設に反対した)" },
    { id: "S3-13", cat: "S3", q: "spread", ans_j: "広げる，広がる", example: "The children spread a large sheet of paper and drew a map of their town. (子供たちは大きな紙を広げ，自分たちの町の地図を描いた)" },
    { id: "S3-14", cat: "S3", q: "suffer", ans_j: "苦しむ，悩む", example: "He is suffering from a bad cold right now. (彼は今ひどい風邪で苦しんでいる)" },
    { id: "S3-15", cat: "S3", q: "deal", ans_j: "扱う，対処する，取引", example: "Do you know any travel agency that deals with trips to China? (中国旅行を扱っている旅行代理店をどこか知っていますか)" },
    { id: "S3-16", cat: "S3", q: "sponsor", ans_j: "後援する，スポンサー", example: "This research is sponsored by the national government. (この研究は政府の後援を受けている)" },
    { id: "S3-17", cat: "S3", q: "celebrate", ans_j: "祝う", example: "The institute had a ceremony to celebrate its hundredth birthday. (その研究所は100回目の創立記念日を祝う式典を開催した)" },
    { id: "S3-18", cat: "S3", q: "precious", ans_j: "大切な，貴重な", example: "Nothing is more precious to me than our children. (私にとって子供たちは何よりも大切です)" },
    { id: "S3-19", cat: "S3", q: "amazing", ans_j: "素晴らしい，驚くべき", example: "This video shows the amazing world of the deep sea. (このビデオは素晴らしい深海の世界を見せてくれる)" },
    { id: "S3-20", cat: "S3", q: "complex", ans_j: "複雑な，複合体，複素数", example: "It is good to solve a complex problem step by step. (複雑な問題は一つ一つ手順を踏んで解くのが良い)" },
    { id: "S3-21", cat: "S3", q: "special", ans_j: "特別な，専門の", example: "You need a special account to access this server. (このサーバーにアクセスするには特別なアカウントが必要です)" },
    { id: "S3-22", cat: "S3", q: "official", ans_j: "公式の，役員", example: "Our company was an official sponsor of the event. (わが社はそのイベントの公式スポンサーだった)" },
    { id: "S3-23", cat: "S3", q: "familiar", ans_j: "よく知っている，習熟している", example: "Everybody here is familiar with computers. (ここにいる誰もがコンピューターについてよく知っている)" },
    { id: "S3-24", cat: "S3", q: "honest", ans_j: "正直な", example: "You must be honest when you pay taxes. (税金の支払いは正直にやりなさい)" },
    { id: "S3-25", cat: "S3", q: "social", ans_j: "社会の，社交的な", example: "Some social problems were discussed at the meeting. (いくつかの社会問題について会議で話し合われた)" },

    // --- Session 4 (ID 851 - 875) ---
    { id: "S4-1", cat: "S4", q: "society", ans_j: "社会，団体", example: "Japan is going to be a super aging society. (日本は超高齢化社会になりつつある)" },
    { id: "S4-2", cat: "S4", q: "border", ans_j: "国境，境界", example: "A battle occurred near the border between the two countries. (２国間の国境付近で戦闘が起こった)" },
    { id: "S4-3", cat: "S4", q: "growth", ans_j: "成長，発展，増加", example: "The medicine stopped the growth of his tumor. (その薬で彼の腫瘍の成長が止まった)" },
    { id: "S4-4", cat: "S4", q: "hypothesis", ans_j: "仮説", example: "The results of this experiment proved our hypothesis. (この実験結果から私たちの仮説は証明された)" },
    { id: "S4-5", cat: "S4", q: "survey", ans_j: "調査，測量，調査する，測量する", example: "We are planning a survey on the environment. (私たちは環境についての調査を計画しています)" },
    { id: "S4-6", cat: "S4", q: "questionnaire", ans_j: "アンケート", example: "We did a questionnaire survey on this issue. (私たちはこの問題についてアンケート調査を行った)" },
    { id: "S4-7", cat: "S4", q: "impact", ans_j: "衝突，衝撃，影響を与える", example: "This picture was taken at the moment of impact. (この写真は衝突の瞬間に撮影された)" },
    { id: "S4-8", cat: "S4", q: "lightning", ans_j: "稲妻", example: "Lightning is likely to strike the tallest thing standing around. (稲妻はその周辺に立っている一番高い物体に落ちやすい)" },
    { id: "S4-9", cat: "S4", q: "thunder", ans_j: "雷", example: "It looks like we are going to have a thunder shower. (どうやら雷雨になりそうな気配です)" },
    { id: "S4-10", cat: "S4", q: "storm", ans_j: "嵐", example: "A big storm hit the island. (大きな嵐がその島を襲った)" },
    { id: "S4-11", cat: "S4", q: "steam", ans_j: "水蒸気，蒸す", example: "Water turns into steam when it is heated. (水は加熱されると水蒸気に変わる)" },
    { id: "S4-12", cat: "S4", q: "ray", ans_j: "光線，～線", example: "A hat protects you from the strong rays of the sun. (帽子は強い太陽光線からあなたを守ります)" },
    { id: "S4-13", cat: "S4", q: "radiation", ans_j: "放射線，（光や熱の）放射", example: "Each of these substances radiates some kind of radiation. (これらの物質はそれぞれある種の放射線を発する)" },
    { id: "S4-14", cat: "S4", q: "layer", ans_j: "層", example: "The X-ray revealed that the picture had three layers of paint. (X線撮影によってその絵には絵の具の層が3層あることがわかった)" },
    { id: "S4-15", cat: "S4", q: "acid", ans_j: "酸，酸性の", example: "Acid is in various kinds of food and drink. (酸はさまざまな種類の食べ物や飲み物に含まれている)" },
    { id: "S4-16", cat: "S4", q: "ion", ans_j: "イオン", example: "There are two kinds of ions in the liquid. (その液体中に２種類のイオンが存在する)" },
    { id: "S4-17", cat: "S4", q: "bond", ans_j: "結合，接着，結合する", example: "An ionic bond is a type of chemical bond. (イオン結合は化学結合の一種である)" },
    { id: "S4-18", cat: "S4", q: "device", ans_j: "機器，装置", example: "A cellular phone is one of the most familiar electronic devices. (携帯電話は最も身近な電子機器の一つです)" },
    { id: "S4-19", cat: "S4", q: "beaker", ans_j: "ビーカー", example: "This beaker can hold strong acids. (このビーカーは強酸物質を入れてもよい)" },
    { id: "S4-20", cat: "S4", q: "lid", ans_j: "ふた", example: "The steam raised the lid of the pot. (蒸気が鍋のふたを持ち上げた)" },
    { id: "S4-21", cat: "S4", q: "memory", ans_j: "記憶（力），記憶装置", example: "He lost his memory of the past in the accident. (彼はその事故で過去の記憶を失った)" },
    { id: "S4-22", cat: "S4", q: "digit", ans_j: "（数字の）桁", example: "Name a three-digit number that can be divided by four. (4で割り切れる3桁の数字をひとつあげなさい)" },
    { id: "S4-23", cat: "S4", q: "aim", ans_j: "目的，目標，狙う", example: "The aim of this study is to know how much radiation the substance releases. (本研究の目的はその物質が発している放射線の量を知ることである)" },
    { id: "S4-24", cat: "S4", q: "affect", ans_j: "影響する，作用する", example: "Magnetism may affect the human body in some way. (磁気は人体に何らかの影響を与えるかもしれない)" },
    { id: "S4-25", cat: "S4", q: "launch", ans_j: "発射する，始める", example: "Apollo 13 was launched on Saturday, April 11, 1970 at 13:13. (アポロ13号は1970年4月11日土曜日の13時13分に打ち上げられた)" }
];